### ISSUE TITLE
Editor 

### ISSUE THREAD

**Issue by gedw99** [ajstarks/decksh#1]
Hey Anthony 

this is rather cool :) 

Cc @Inkeliz was talking about adobe XD , but I was thinking that it might be possible to get deck round tripping as a wysiwyg designer.

Gio display of a deck could have property highlights and when you change a property is generates the dsl and re renders 

this is an oversimplification but I am just trying to get the idea across 

a more robust way would be for the property editor to generate an event , and the DSL listener would then update the correct part of the dsl, and then send  commands to the gio Renderer to also update.

this flow of 1 event and many commands is exactly how event sourcing with the command pattern works and allows a nice balance of loose coupling and reuse.  

So the DSL is the write side, and the GIO is the read only side. 

So if you started with a blank GUI, and you use the Property Editor to add a "AppBar" or whatever, an even for this is sent, the DSL updates, and a command ( or however many) is sent to the GIO gui to update. Because GIO is retained mode it makes it very easy to do this. Its just a command event that it listens to to update in its render loop. 

For another way to look at it:
This is how a DB works also. In a DB you have a Table, and you have a Materialized View. When you change the table, the Materialized View updates magically. But the CUD ( Create, Update, Delete) event happened inside the DB to update the Materialized View.   So for each "element" in the GIO you can do a CUD command ( Create, Update or Delete ).

This pattern is also how you can get Actions working with a WYSIWYG GUi i think. You just apply the same pattern to the data layer. I can go into more detail about this later...

How this gets the concept across ?

Curious if your into the idea ? 

If i have not explained this pattern well enough just ask ...

**Comment by gedw99** [comment]
Cc @Inkeliz

**Comment by gedw99** [comment]
I think that this would be a basis for incorporating Adobe XD too alter BTW.   

Because you have the separation of concerns via the Event / Commands system you can accommodate the different between the adobe format and the GIO rendering system.

**Comment by ajstarks** [comment]
I've always wanted to use gio as a front-end to deck.  See: https://github.com/ajstarks/deck/tree/master/cmd/gcdeck  it's not really ready -- the event system does not work correctly, and there are some rendering issues.   It does include signal processing so that when it sees a SIGHUP, it's supposed to re-render.  This is how mupdf works.  My current decksh workflow is to edit the decksh source in an editor, and arrange to send the signal when the decksh source changes.  (I use entr (https://eradman.com/entrproject/) as the watcher:  
```
echo foo.dsh | entr -s 'decksh foo.dsh | pdfdeck -stdout - > f.pdf && pkill -HUP mupdf'
```

Alternatively, you should be able to build a gio GUI that generates deck markup.

**Comment by gedw99** [comment]
Hey @ajstarks 

thanks for that info. Makes sense to me in terms of signaling and reloading. Did any of what i write about events / commands appeal to you though ? 

I will try out the various deck tools next week, and look at some aspects of this.

**Comment by ajstarks** [comment]
hello, @gedw99 .  Here are some documents to help you use deck/decksh:

https://speakerdeck.com/ajstarks/decksh-object-reference

and 

https://speakerdeck.com/ajstarks/pdfdeck

which has more on the workflow.  

Yes, your ideas are interesting.  Re: listening/rendering: are you thinking of maintaining a list of objects to render, or just scan and render what's on the canvas at any given time.

**Comment by gedw99** [comment]
Thanks . I got the stack running  it will check out the slides anyway .

regarding your question … I think that a json schema is needed for each object so that the designer gui can present properties with restrictions and validations . 

Then change event is generated for the backend to process . The DSL markup is then updated and then the commands generated and sent to the front end . I am not sure yet as to the logic of the commands though . Need to dig deeper into the structure of deck . That’s all I can theorise so far until I spend some time on it next week

**Comment by gedw99** [comment]
The base Schema: https://github.com/ajstarks/deck looks nice and simple.

looks like there is no knowledge of what can be inside what ? if correct, a JSON Schema is needed to describe this also.

**Comment by gedw99** [comment]
https://github.com/nats-io/jsm.go and https://github.com/nats-io/natscli show one way of thinking about event / command system for making the Editor system.

BTW, Dont get confused about the fact that NATS IS a PUB SUb System.  You use io.reader / writer and thats all great. 

The JSON Schema describes the system / control plane of itself using json schema and commands in order to make the system easy to extend, but also so that the system is self responsive ( like a GUI Editor ). This is the point of it. The json schema and the events all eventually map to Golang objects.

**Comment by gedw99** [comment]
The other way that the events structure could be is this gebeichtetem structure.

https://github.com/simpleiot/simpleiot/blob/master/data/node.go

nodes have points and a type !

That is designed to des robe a change to both the markup ( dsl ) and possibly the commands to update the GUI.

it’s not perfect but shows an approach . 

Points is designed for IOT devices sending data and receiving data , so it’s not quite enough I suspect .

**Comment by gedw99** [comment]
https://github.com/alda-lang/alda

Has its own markup languages, plus a means to describe changes to the markup.

**Comment by ajstarks** [comment]
Re: schema, the entire structure is defined in lines 12-126 of deck.go

**Comment by gedw99** [comment]
Ok makes sense

https://github.com/alda-lang/alda looks so far like a very good match for the problem domain. Only been at it for 10 minutes, but so far so good. 

https://github.com/alda-lang/alda/blob/master/client/model/score.go#L13 models the updating from his markdown 

https://github.com/alda-lang/alda/blob/master/client/cmd/parse.go is a cmd to try out that aspect.

**Comment by gedw99** [comment]
> https://github.com/ajstarks/deck

thanks. will have a look

**Comment by gedw99** [comment]
> Re: schema, the entire structure is defined in lines 12-126 of deck.go

thanks will check it out.

**Comment by gedw99** [comment]
> hello, @gedw99 . Here are some documents to help you use deck/decksh:
> 
> https://speakerdeck.com/ajstarks/decksh-object-reference
> 
> and
> 
> https://speakerdeck.com/ajstarks/pdfdeck
> 
> which has more on the workflow.
> 
> Yes, your ideas are interesting. Re: listening/rendering: are you thinking of maintaining a list of objects to render, or just scan and render what's on the canvas at any given time.

I had a play with deck and the many other outputs ( pdf, svg, etc) for an hour. It looks like its setup to pipeone into the other like a pipeline.

I think you need events . Here is the flow for the events idea.

Start --> MARKUP ( your xml that you have now ) --> RENDERING CANVAS ( the actual final look) --> CHANGE EVENTS ( that the user created by using a property grid to edit the property of a rectangle --> Back to the start

Chris's Markdown example does some of the flow but not all of it.
https://github.com/gioui/gio-example/blob/main/markdown/main.go
The TextState is basically holding the events... 
THen on https://github.com/gioui/gio-example/blob/main/markdown/main.go#L114 he checks for the new change events in TextState.

Chris's example has the MARKUP ( markdown in his case )  on the left and the RENDERING CANVAS on the right.
But really what is needed is that the RENDERING CANVAS should have a property grid. The user clicks on a "element" like a H1 heading, and then the property grid ( sheet in Material Design world) shows all the properties for a H1. The user then changes some property, which in this case is only the actual text.  The event would then be created to represent this change. The MARKUP would listes for the change event, updates its markdown, and the RENDERING CANVAS updates.  

If you run his example the stuff above will make sense.

In terms of event systems i would use NATS, because then you can have 100's of editors on the same doc in real time.
There is now a version that works with wasm over at matrix. 
https://github.com/matrix-org/dendrite/tree/nats
It even models key presses !!!!   Check it out.
