### ISSUE TITLE
wasm and wasi tinygo compilation fails due to xml reflection when encoding.

### ISSUE THREAD

**Issue by gedw99** [ajstarks/decksh#2]
The xml generation is blocking compilation to wasm and wasi.

Am playing around with building a basic editor and want to run decksh in the browser, so its easier for people to use.
Doing compilation stages in the browser makes the editor experience much faster for the user.

This is compiling ./decksh/cmd/decksh/. to WASM using tinygo.

```
tinygo build -o decksh.wasm -target wasm .
# encoding/xml
/usr/local/opt/go/libexec/src/encoding/xml/typeinfo.go:318:14: typ.FieldByIndex undefined (type reflect.Type has no field or method FieldByIndex)
/usr/local/opt/go/libexec/src/encoding/xml/typeinfo.go:319:14: typ.FieldByIndex undefined (type reflect.Type has no field or method FieldByIndex)
``` 

Its when the xml is saved. This is really common problem with tinygo. need to see if there is equivalent for xml :)
Its a well known limitation https://tinygo.org/docs/reference/lang-support/stdlib/#encodingxml

everyone uses https://github.com/buger/jsonparser for json encoding and decoding with tinygo. Its much faster at runtime too due to not using reflect.

**Comment by gedw99** [comment]
https://github.com/ajstarks/deck/blob/master/deck.go is using struct tags and decksh imports and calls this for the generation. 
Also the utils package / repo  also has xml related code

**Comment by gedw99** [comment]
here is the IDE: https://github.com/zalify/easy-email

Its react but shows the concept, as well as how a merge happens on a user changing something.

This is using json, not xml though.

But i am planning to build the equivalent with gioui, rather than react.

**Comment by gedw99** [comment]
2.9M  decksh.wasm is 2.9 MB when compiled with the standard go wasm compiler, after compression. stripping debug symbols makes no size difference.

I suspect that the use of fmt everywhere is also bloating the size.

**Comment by gedw99** [comment]
@ajstarks 
If you are not at all interested in getting this working for WASM compilation, just let me know.

**Comment by ajstarks** [comment]
Note that decksh does it's own XML generation without using encoding/xml.

**Comment by gedw99** [comment]
good point.. I thought i was going crazy initially cause there was no import of "encoding/xml" ....but the github.com/ajstarks/decksh go.mod imports bring in other things that do use the xml encoder from what i can see.

**Comment by gedw99** [comment]
do you have any ideas on this ?

what i see are:
- wait until tinygo support xml encode / decode
- just use the standard golang compiler to wasm.
- change out the xml to json and use the json compiler that does already support tinygo.

**Comment by gedw99** [comment]
Hey @ajstarks this xml golang pkg can do xml encode / decode and get around the wasm tinygo issue perhaps. going to try it out.

https://github.com/beevik/etree
