### ISSUE TITLE
Integrity checker 

### ISSUE THREAD

**Issue by gedw99** [ajstarks/decksh#3]
Would be good if a dsh with bad links is discoverable. Or also bad includes or bad variables or unused variable. 

I just noticed how often dsh files break when refactoring them..

Test.dsh is broken again for example . Goes nuts on page 8 or 9 when using gcdeck to view it.

**Comment by ajstarks** [comment]
can you show the error message (if any). Also, please make sure to use the latest decksh (I recently added a new keyword).

**Comment by gedw99** [comment]
ok cool. I  did not see an error, but i can check again and put here...

I am on latest always :)

here is how i got the bug:

1. use gcdeck
2. run test.dsh through it.
3.  on page 8 or 9 its goes nuts and starts playing all the pages.

its the same bug we had 2 weeks ago..

**Comment by gedw99** [comment]
> what happens with pdfdeck?

its happy chappy. no probs.

**Comment by gedw99** [comment]
here we go:

BUG: in gcdeck, it gets to page 8 or 9 it then pages forward non stop when you click.

``` 
decksh test.dsh > test.xml
gcdeck -pagesize A4 test.xml
```

https://github.com/ajstarks/decksh/assets/53147028/684b3238-e968-4c57-9eaf-bf5a6d82cda1

**Comment by ajstarks** [comment]
yes, I can reproduce this.  This is not a decksh bug, but how gcdeck is handling events.
I will investigate.  I will close this one and open a deck/gcdeck bug.

**Comment by gedw99** [comment]
ok thanks

**Comment by ajstarks** [comment]
fixed in https://github.com/ajstarks/deck/commit/ebe7b794a4b1d6b5f0fda548aa580003cb4c16d2

**Comment by gedw99** [comment]
Thank @ajstarks 

will give it a try and feedback

**Comment by gedw99** [comment]
@ajstarks 

is working for me too.

cheers
