### ISSUE TITLE
decksh@v0.0.0-20240608190944-cee04a20277d/generate.go:1344:22: chart.Boundary undefined (type dchart.Settings has no field or method Boundary)

### ISSUE THREAD

**Issue by TafThorne** [ajstarks/decksh#6]
It seems that decksh v0.0.0-20240608190944-cee04a20277d is trying to use a Boundary field which does not exist in the version of dchart it has listed in its go.mod file.  

```
$ go install github.com/ajstarks/decksh/cmd/decksh@latest
# github.com/ajstarks/decksh
/home/thomasth/go/pkg/mod/github.com/ajstarks/decksh@v0.0.0-20240608190944-cee04a20277d/generate.go:1344:22: chart.Boundary undefined (type dchart.Settings has no field or method Boundary)
/home/thomasth/go/pkg/mod/github.com/ajstarks/decksh@v0.0.0-20240608190944-cee04a20277d/generate.go:1394:15: chart.Boundary undefined (type dchart.Settings has no field or method Boundary)
/home/thomasth/go/pkg/mod/github.com/ajstarks/decksh@v0.0.0-20240608190944-cee04a20277d/generate.go:1395:61: undefined: dchart.Parsebounds
/home/thomasth/go/pkg/mod/github.com/ajstarks/decksh@v0.0.0-20240608190944-cee04a20277d/generate.go:1395:79: chart.Boundary undefined (type dchart.Settings has no field or method Boundary)
```

Currently (cee04a) decksh's go.mod requires `github.com/ajstarks/dchart v0.0.0-20230918170725-f04acc8d9991`  but boundary was only added within the past few days

**Comment by ajstarks** [comment]
Ok. I updated dchart with https://github.com/ajstarks/dchart/commit/050a313a5d4b81d9928cb6867d6765f14cd9d917 I've now updated go.mod, and go.sum.  It should work now.

**Comment by TafThorne** [comment]
Thank you for the swift repair.  I can confirm that the install now works for me as expected.
